on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.2.8', '9.4.8', '9.6.6', '9.8.2', '9.10.1']
        cabal: ['3.10.3.0']
        os: [ubuntu-latest]
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Configure
        run: |
          cabal configure --enable-tests --enable-benchmarks --test-show-details=direct

      - name: Freeze
        run: |
          cabal freeze

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ matrix.cabal }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ matrix.cabal }}-
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-

      - name: Install dependencies
        run: |
          cabal build all --only-dependencies

      - name: Build
        run: |
          cabal build all

      - name: Test
        run: |
          cabal test all
